//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimerAppAspMVCTiempoReal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDCursoEntities : DbContext
    {
        public BDCursoEntities()
            : base("name=BDCursoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriaCurso> CategoriaCurso { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<SeccionCurso> SeccionCurso { get; set; }
        public virtual DbSet<VideosSeccion> VideosSeccion { get; set; }
    }
}
