//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimerAppAspMVCTiempoReal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideosSeccion
    {
        public int IIDVIDEOS { get; set; }
        public string NOMBRE { get; set; }
        public string VIDEO { get; set; }
        public string ENLACE { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
        public Nullable<int> IIDSECCION { get; set; }
    
        public virtual SeccionCurso SeccionCurso { get; set; }
    }
}
